# Generated by Django 6.0.1 on 2026-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismpoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourismpoint',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourismpoint',
            name='open_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourismpoint',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
