# Generated by Django 6.0.1 on 2026-03-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0002_tourismpoint_address_tourismpoint_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismpoint",
            name="menu_imgs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
