# Generated by Django 6.0.1 on 2026-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0002_tourismpoint_address_tourismpoint_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismpoint',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
