# Generated by Django 6.0.1 on 2026-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0003_tourismpoint_menu_imgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourismpoint",
            name="menu_imgs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
