# Generated by Django 6.0.1 on 2026-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0003_alter_tourismpoint_img"),
        ("AppGIS", "0004_alter_tourismpoint_menu_imgs"),
    ]

    operations = []
