# Generated by Django 6.0.1 on 2026-03-21 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0005_merge_20260310_1613"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_path", models.CharField(max_length=200)),
                ("caption", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.CharField(max_length=20)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("rating", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="tourismpoint",
            name="type",
        ),
        migrations.AddField(
            model_name="tourismpoint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppGIS.category",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tourismpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppGIS.tourismpoint"
            ),
        ),
        migrations.AddField(
            model_name="imagegallery",
            name="tourismpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppGIS.tourismpoint"
            ),
        ),
        migrations.AddField(
            model_name="openinghours",
            name="tourismpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppGIS.tourismpoint"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="tourismpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppGIS.tourismpoint"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
