# Generated by Django 6.0.1 on 2026-03-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0006_category_event_imagegallery_openinghours_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
