# Generated by Django 6.0.1 on 2026-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0007_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismpoint',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá từ'),
        ),
    ]
