# Generated by Django 6.0.1 on 2026-03-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0008_tourismpoint_price"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="AppGIS_review",
        ),
    ]
