# Generated by Django 6.0.1 on 2026-03-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0009_alter_review_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagegallery",
            name="tourismpoint",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="ImageGallery",
        ),
    ]
