# Generated by Django 6.0.1 on 2026-03-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0010_remove_imagegallery_tourismpoint_delete_event_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpeningHours",
        ),
    ]
