# Generated by Django 6.0.1 on 2026-03-31 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0011_delete_openinghours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tourism_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "tourismpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="AppGIS.tourismpoint",
                    ),
                ),
            ],
        ),
    ]
