# Generated by Django 6.0.1 on 2026-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0012_imagegallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourismpoint",
            name="open_hours",
        ),
        migrations.AddField(
            model_name="tourismpoint",
            name="close_time",
            field=models.TimeField(default="22:00"),
        ),
        migrations.AddField(
            model_name="tourismpoint",
            name="open_time",
            field=models.TimeField(default="09:00"),
        ),
    ]
