# Generated by Django 6.0.1 on 2026-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0013_remove_tourismpoint_open_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên người gửi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
        ),
    ]
