# Generated by Django 6.0.1 on 2026-04-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0014_tour_tourbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tour",
            name="tag",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
