# Generated by Django 6.0.1 on 2026-04-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0015_tour_duration_tour_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tour",
            old_name="desc",
            new_name="description",
        ),
    ]
