# Generated by Django 6.0.1 on 2026-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0016_rename_desc_tour_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourbooking",
            name="guests",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tourbooking",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourbooking",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
