# Generated by Django 6.0.1 on 2026-04-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0014_contactmessage'),
        ('AppGIS', '0017_tourbooking_guests_tourbooking_start_date_and_more'),
    ]

    operations = [
    ]
