# Generated by Django 6.0.1 on 2026-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0018_merge_20260402_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
