# Generated by Django 6.0.1 on 2026-04-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0019_tourbooking_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageGallery",
        ),
    ]
