# Generated by Django 6.0.1 on 2026-04-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0020_delete_imagegallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="tourismpoint",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
