# Generated by Django 6.0.1 on 2026-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0021_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tour/"),
        ),
        migrations.AddField(
            model_name="tour",
            name="short_intro",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
