# Generated by Django 6.0.1 on 2026-04-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0021_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismpoint',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
    ]
