# Generated by Django 6.0.1 on 2026-04-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0021_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tên sự kiện")),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="events/main/", verbose_name="Ảnh bìa chính"
                    ),
                ),
                ("description", models.TextField(verbose_name="Mô tả sự kiện")),
                ("location", models.CharField(max_length=255, verbose_name="Địa điểm")),
                ("latitude", models.FloatField(verbose_name="Vĩ độ")),
                ("longitude", models.FloatField(verbose_name="Kinh độ")),
                ("start_date", models.DateTimeField(verbose_name="Ngày bắt đầu")),
                ("end_date", models.DateTimeField(verbose_name="Ngày kết thúc")),
            ],
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="AppGIS.event",
                    ),
                ),
            ],
        ),
    ]
