# Generated by Django 6.0.1 on 2026-04-16 04:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0022_tour_image_tour_short_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=6,
            ),
        ),
    ]
