# Generated by Django 6.0.1 on 2026-04-16 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0022_event_eventimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="main_image",
            field=models.ImageField(
                upload_to="tourism/main/", verbose_name="Ảnh chính"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Tên sự kiện"),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(upload_to="tourism/gallery/"),
        ),
    ]
