# Generated by Django 6.0.1 on 2026-04-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0022_tourismpoint_phone"),
        ("AppGIS", "0023_tour_images"),
    ]

    operations = []
