# Generated by Django 6.0.1 on 2026-04-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0022_tourismpoint_phone"),
        ("AppGIS", "0023_event_created_at_alter_event_main_image_and_more"),
    ]

    operations = []
