# Generated by Django 6.0.1 on 2026-04-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0024_merge_20260416_1231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(upload_to="events/gallery/"),
        ),
    ]
