# Generated by Django 6.0.1 on 2026-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0026_event_description_event_end_date_event_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(default="Văn hóa", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(default="Sắp diễn ra", max_length=50),
        ),
    ]
