# Generated by Django 6.0.1 on 2026-04-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0024_merge_0022_tourismpoint_phone_0023_tour_images"),
        ("AppGIS", "0027_event_category_event_status"),
    ]

    operations = []
