# Generated by Django 6.0.1 on 2026-04-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0028_merge_20260420_1011"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Về Hệ Thống Web GIS Thông Minh", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Kiến tạo nền tảng số dựa trên dữ liệu không gian",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Chúng tôi cung cấp giải pháp bản đồ tương tác hiện đại, giúp biến dữ liệu địa lý phức tạp thành những thông tin trực quan, dễ tiếp cận cho mọi người."
                    ),
                ),
                ("vision_title", models.CharField(default="Tầm nhìn", max_length=100)),
                (
                    "vision_text",
                    models.TextField(
                        default="Trở thành nền tảng bản đồ số hàng đầu, hỗ trợ đắc lực trong việc tra cứu thông tin địa lý và ra quyết định dựa trên dữ liệu."
                    ),
                ),
                ("mission_title", models.CharField(default="Sứ mệnh", max_length=100)),
                (
                    "mission_text",
                    models.TextField(
                        default="Số hóa dữ liệu hạ tầng và du lịch nhằm minh bạch hóa thông tin, giúp người dùng tối ưu hóa lộ trình di chuyển."
                    ),
                ),
                (
                    "values_title",
                    models.CharField(default="Giá trị cốt lõi", max_length=100),
                ),
                (
                    "values_text",
                    models.TextField(
                        default="Dữ liệu chính xác - Công nghệ tiên tiến - Trải nghiệm người dùng mượt mà trên mọi thiết bị."
                    ),
                ),
                (
                    "stats_data_points",
                    models.CharField(default="1,000+", max_length=50),
                ),
                ("stats_accuracy", models.CharField(default="99.9%", max_length=50)),
                (
                    "stats_response_time",
                    models.CharField(default="0.5s", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Nội dung trang About",
                "verbose_name_plural": "Nội dung trang About",
            },
        ),
        migrations.AlterField(
            model_name="tour",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
