# Generated by Django 6.0.1 on 2026-04-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0029_aboutcontent_alter_tour_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcontent",
            name="stats_accuracy_label",
            field=models.CharField(default="Độ chính xác tọa độ", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="stats_data_label",
            field=models.CharField(default="Điểm dữ liệu địa lý", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="stats_response_label",
            field=models.CharField(default="Tốc độ phản hồi", max_length=100),
        ),
    ]
