# Generated by Django 6.0.1 on 2026-04-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0030_aboutcontent_stats_accuracy_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_button",
            field=models.CharField(default="KHÁM PHÁ BẢN ĐỒ NGAY", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_text",
            field=models.TextField(default="Sẵn sàng khám phá những địa điểm thú vị?"),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step1_text",
            field=models.TextField(
                default="Dữ liệu được tích hợp từ các nguồn tin cậy và tệp tin GeoJSON chuẩn."
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step1_title",
            field=models.CharField(default="Thu thập", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step2_text",
            field=models.TextField(
                default="GeoPandas & Django thực hiện các thuật toán phân tích không gian phức tạp."
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step2_title",
            field=models.CharField(default="Xử lý", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step3_text",
            field=models.TextField(
                default="Folium trực quan hóa kết quả lên bản đồ nền tương tác sinh động."
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="step3_title",
            field=models.CharField(default="Hiển thị", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech1_desc",
            field=models.CharField(default="Hiển thị bản đồ tương tác", max_length=200),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech1_name",
            field=models.CharField(default="Folium & Leaflet", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech2_desc",
            field=models.CharField(default="Phân tích dữ liệu GIS", max_length=200),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech2_name",
            field=models.CharField(default="GeoPandas", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech3_desc",
            field=models.CharField(
                default="Xử lý tọa độ & Khoảng cách", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech3_name",
            field=models.CharField(default="GeoPy & PyProj", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech4_desc",
            field=models.CharField(default="Backend Framework", max_length=200),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech4_name",
            field=models.CharField(default="Django 6.0", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="tech_title",
            field=models.CharField(default="Nền Tảng Công Nghệ", max_length=200),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="workflow_title",
            field=models.CharField(
                default="Hệ Thống Hoạt Động Thế Nào?", max_length=200
            ),
        ),
    ]
