# Generated by Django 6.0.1 on 2026-04-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0031_aboutcontent_cta_button_aboutcontent_cta_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Sắp diễn ra", "Sắp diễn ra"),
                    ("Đang diễn ra", "Đang diễn ra"),
                    ("Tạm hoãn", "Tạm hoãn"),
                    ("Đã kết thúc", "Đã kết thúc"),
                ],
                default="Sắp diễn ra",
                max_length=50,
            ),
        ),
    ]
