# Generated by Django 6.0.1 on 2026-04-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGIS", "0028_merge_20260416_2246"),
        ("AppGIS", "0032_alter_event_status"),
    ]

    operations = []
