# Generated by Django 6.0.1 on 2026-04-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGIS', '0033_merge_20260420_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
    ]
